#ifndef RSAENCRYPTION_GLOBAL_H
#define RSAENCRYPTION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RSAENCRYPTION_LIBRARY)
#  define RSAENCRYPTIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define RSAENCRYPTIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // RSAENCRYPTION_GLOBAL_H
