#ifndef CALCFORMULA_GLOBAL_H
#define CALCFORMULA_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CALCFORMULA_LIBRARY)
#  define CALCFORMULASHARED_EXPORT Q_DECL_EXPORT
#else
#  define CALCFORMULASHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CALCFORMULA_GLOBAL_H
