#ifndef ELSEIFSTEP_GLOBAL_H
#define ELSEIFSTEP_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ELSEIFSTEP_LIBRARY)
#  define ELSEIFSTEPSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ELSEIFSTEPSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ELSEIFSTEP_GLOBAL_H
    
    