#ifndef KEYPARAMSHOWSTEP_GLOBAL_H
#define KEYPARAMSHOWSTEP_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(KEYPARAMSHOWSTEP_LIBRARY)
#  define KEYPARAMSHOWSTEPSHARED_EXPORT Q_DECL_EXPORT
#else
#  define KEYPARAMSHOWSTEPSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // KEYPARAMSHOWSTEP_GLOBAL_H
    
    