#ifndef TEMPERATUREMODEL_GLOBAL_H
#define TEMPERATUREMODEL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TEMPERATUREMODEL_LIBRARY)
#  define TEMPERATUREMODELSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TEMPERATUREMODELSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TEMPERATUREMODEL_GLOBAL_H
    
    