#ifndef DIGITALIOADAPTER_GLOBAL_H
#define DIGITALIOADAPTER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DIGITALIOADAPTER_LIBRARY)
#  define DIGITALIOADAPTERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DIGITALIOADAPTERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DIGITALIOADAPTER_GLOBAL_H
    
    