#ifndef VARIABLEFRAME_GLOBAL_H
#define VARIABLEFRAME_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(VARIABLEFRAME_LIBRARY)
#  define VARIABLEFRAMESHARED_EXPORT Q_DECL_EXPORT
#else
#  define VARIABLEFRAMESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // VARIABLEFRAME_GLOBAL_H
