#ifndef ICDFRAMEADAPTER_GLOBAL_H
#define ICDFRAMEADAPTER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ICDFRAMEADAPTER_LIBRARY)
#  define ICDFRAMEADAPTERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ICDFRAMEADAPTERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ICDFRAMEADAPTER_GLOBAL_H
