#ifndef ZMQSENDADAPTER_GLOBAL_H
#define ZMQSENDADAPTER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ZMQSENDADAPTER_LIBRARY)
#  define ZMQSENDADAPTERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ZMQSENDADAPTERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ZMQSENDADAPTER_GLOBAL_H
    
    