#ifndef MULTICASTADAPTER_GLOBAL_H
#define MULTICASTADAPTER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MULTICASTADAPTER_LIBRARY)
#  define MULTICASTADAPTERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MULTICASTADAPTERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MULTICASTADAPTER_GLOBAL_H
    
    