#ifndef VIRTUALUNICASTADAPTER_GLOBAL_H
#define VIRTUALUNICASTADAPTER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(VIRTUALUNICASTADAPTER_LIBRARY)
#  define VIRTUALUNICASTADAPTERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define VIRTUALUNICASTADAPTERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // VIRTUALUNICASTADAPTER_GLOBAL_H
    
    