#ifndef SETANALOGOUTSTEP_GLOBAL_H
#define SETANALOGOUTSTEP_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SETANALOGOUTSTEP_LIBRARY)
#  define SETANALOGOUTSTEPSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SETANALOGOUTSTEPSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SETANALOGOUTSTEP_GLOBAL_H
    
    