#ifndef ZMQRCVADAPTER_GLOBAL_H
#define ZMQRCVADAPTER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ZMQRCVADAPTER_LIBRARY)
#  define ZMQRCVADAPTERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ZMQRCVADAPTERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ZMQRCVADAPTER_GLOBAL_H
    
    