#ifndef SERIALPORTADAPTER_GLOBAL_H
#define SERIALPORTADAPTER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SERIALPORTADAPTER_LIBRARY)
#  define SERIALPORTADAPTERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SERIALPORTADAPTERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SERIALPORTADAPTER_GLOBAL_H
    
    