#ifndef TEMPERATURESTEP_GLOBAL_H
#define TEMPERATURESTEP_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TEMPERATURESTEP_LIBRARY)
#  define TEMPERATURESTEPSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TEMPERATURESTEPSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TEMPERATURESTEP_GLOBAL_H
    
    