#ifndef ANALOGOUT_GLOBAL_H
#define ANALOGOUT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ANALOGOUT_LIBRARY)
#  define ANALOGOUTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ANALOGOUTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ANALOGOUT_GLOBAL_H
