#ifndef FORMULACALCSTEP_GLOBAL_H
#define FORMULACALCSTEP_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FORMULACALCSTEP_LIBRARY)
#  define FORMULACALCSTEPSHARED_EXPORT Q_DECL_EXPORT
#else
#  define FORMULACALCSTEPSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FORMULACALCSTEP_GLOBAL_H
    
    