#ifndef DYNCREATE_GLOBAL_H
#define DYNCREATE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DYNCREATE_LIBRARY)
#  define DYNCREATESHARED_EXPORT Q_DECL_EXPORT
#else
#  define DYNCREATESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DYNCREATE_GLOBAL_H
