#ifndef M1553ADAPTER_GLOBAL_H
#define M1553ADAPTER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(M1553ADAPTER_LIBRARY)
#  define M1553ADAPTERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define M1553ADAPTERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // M1553ADAPTER_GLOBAL_H
