#ifndef TCPSERVERADAPTER_GLOBAL_H
#define TCPSERVERADAPTER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TCPSERVERADAPTER_LIBRARY)
#  define TCPSERVERADAPTERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TCPSERVERADAPTERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TCPSERVERADAPTER_GLOBAL_H
