#ifndef JUDGEMULTISTEP_GLOBAL_H
#define JUDGEMULTISTEP_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(JUDGEMULTISTEP_LIBRARY)
#  define JUDGEMULTISTEPSHARED_EXPORT Q_DECL_EXPORT
#else
#  define JUDGEMULTISTEPSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // JUDGEMULTISTEP_GLOBAL_H
    
    