#ifndef PARAMSTABLE_GLOBAL_H
#define PARAMSTABLE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PARAMSTABLE_LIBRARY)
#  define PARAMSTABLESHARED_EXPORT Q_DECL_EXPORT
#else
#  define PARAMSTABLESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PARAMSTABLE_GLOBAL_H
