#ifndef GETSWITCHINSTEP_GLOBAL_H
#define GETSWITCHINSTEP_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GETSWITCHINSTEP_LIBRARY)
#  define GETSWITCHINSTEPSHARED_EXPORT Q_DECL_EXPORT
#else
#  define GETSWITCHINSTEPSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GETSWITCHINSTEP_GLOBAL_H
    
    