#ifndef GENERALFRAME_GLOBAL_H
#define GENERALFRAME_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GENERALFRAME_LIBRARY)
#  define GENERALFRAMESHARED_EXPORT Q_DECL_EXPORT
#else
#  define GENERALFRAMESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GENERALFRAME_GLOBAL_H
