#ifndef SETSWITCHOUTSTEP_GLOBAL_H
#define SETSWITCHOUTSTEP_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SETSWITCHOUTSTEP_LIBRARY)
#  define SETSWITCHOUTSTEPSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SETSWITCHOUTSTEPSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SETSWITCHOUTSTEP_GLOBAL_H
    
    