#ifndef MODELMANAGER_GLOBAL_H
#define MODELMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MODELMANAGER_LIBRARY)
#  define MODELMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MODELMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MODELMANAGER_GLOBAL_H
