#ifndef GETANALOGINSTEP_GLOBAL_H
#define GETANALOGINSTEP_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GETANALOGINSTEP_LIBRARY)
#  define GETANALOGINSTEPSHARED_EXPORT Q_DECL_EXPORT
#else
#  define GETANALOGINSTEPSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GETANALOGINSTEP_GLOBAL_H
    
    